#!/usr/bin/env ruby
####
## relay bot
##
## Copyright (c) 2013 Andrew Northall
##
## MIT License
## See LICENSE file for details.
####

$:.unshift File.dirname(__FILE__)

require 'yaml'
require 'cinch'
require 'cinch/plugins/identify'
require 'lib/relay'
require 'lib/logger'

$config = YAML.load_file("config/config.yaml")
$bots = Hash.new
$zncs = Hash.new
$threads = Array.new
$start = Time.now.to_i

# Make server names all downcase
servers = {}
$config["servers"].each do |k, v|
  servers.merge!({k.downcase => v}) 
end
$config["servers"] = servers

# Make ignore names all downcase
names = $config["ignore"]["nicks"].map { |v| v.downcase }
$config["ignore"]["nicks"] = names

# Set up a bot for each server
$config["servers"].each do |name, server|
  bot = Cinch::Bot.new do
    configure do |c|
      c.nick = server["nick"] || $config["bot"]["nick"]
      c.user = server["user"] || $config["bot"]["user"]
      c.realname = server["realname"] || $config["bot"]["realname"]
      c.password = server["password"] unless server["password"].nil?
      c.server = server["server"]
      c.ssl.use = server["ssl"]
      c.port = server["port"]
      c.channels = [server["channel"]]
      opts = server["msgspersec"] || $config["bot"]["msgspersec"] || nil
      c.messages_per_second = opts unless opts.nil?
      nsname = server["nickservname"] || $config["bot"]["nickservname"] || c.nick
      unless server["sasl"] == false
        c.sasl.username = nsname
        c.sasl.password = server["nickservpass"] || $config["bot"]["nickservpass"]
        c.plugins.plugins = [RelayPlugin]
      else
        c.plugins.plugins = [RelayPlugin, Cinch::Plugins::Identify]
        c.plugins.options[Cinch::Plugins::Identify] = {
          :password => $config["bot"]["nickservpass"],
          :type     => :nickserv,
        }
      end
    end
  end
  bot.loggers.clear
  bot.loggers << RelayLogger.new(name, File.open("log/irc-#{name.downcase}.log", "a"))
  bot.loggers << RelayLogger.new(name, STDOUT)
  bot.loggers.level = :info
  $bots[name] = bot
end

# Start the bots

$bots.each do |key, bot|
  $threads << Thread.new { bot.start }
end

$threads.each { |t| t.join } # wait for other threads
